version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data_container:/data/db
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/admin
      - JWT_SECRET=your_jwt_secret
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongodb_data_container:
